/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  type GetPingResponce,
  GetPingResponceFromJSON,
  GetPingResponceToJSON,
} from "../models";

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {
  /**
   * Get Ping
   */
  async getPingRaw(
    initOverrides?: RequestInit | runtime.InitOverideFunction,
  ): Promise<runtime.ApiResponse<GetPingResponce>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/ping`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetPingResponceFromJSON(jsonValue),
    );
  }

  /**
   * Get Ping
   */
  async getPing(
    initOverrides?: RequestInit | runtime.InitOverideFunction,
  ): Promise<GetPingResponce> {
    const response = await this.getPingRaw(initOverrides);
    return await response.value();
  }
}
