openapi: 3.0.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /ping:
    get:
      summary: Get Ping
      operationId: get_ping
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPingResponce'
  /oauth/redirect-uri:
    get:
      tags:
        - oauth
      summary: Get Oauth Redirect
      description: |-
        認証画面へリダイレクトするためのリダイレクト先のurlを返すAPI．
        このAPIを叩くとセッションが作られる
      operationId: get_oauth_redirect_uri
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOAuthRedirectResponse'
  /oauth/callback:
    get:
      tags:
        - oauth
      summary: Get Oauth Callback
      description: 認証画面を通過して得たcodeを用いてアクセストークンを得る
      operationId: get_oauth_callback
      security:
        - SessionCookie: []
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
            title: Code
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /oauth/me:
    get:
      tags:
        - oauth
      summary: Get Oauth Me
      description: 認証が通らなかったら401が帰ってくる...はず
      operationId: get_oauth_me
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMeResponseFromTraq'
      security:
        - SessionCookie: []
  /dish/{id}:
    get:
      tags:
        - dish
      summary: Get Dish Image
      operationId: get_dish
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            title: Id
      responses:
        '200':
          description: Successful Response
          content:
            image/png: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    GetMeResponseFromTraq:
      properties:
        id:
          type: string
          title: Id
        name:
          type: string
          title: Name
        displayName:
          type: string
          title: Displayname
        iconFileId:
          type: string
          title: Iconfileid
        twitterId:
          type: string
          title: Twitterid
      type: object
      required:
        - id
        - name
        - displayName
        - iconFileId
        - twitterId
      title: GetMeResponseFromTraq
      description: post_o_auth2_token のレスポンスの型
    GetOAuthRedirectResponse:
      properties:
        redirect_uri:
          type: string
          title: Redirect Uri
      type: object
      required:
        - redirect_uri
      title: GetOAuthRedirectResponse
    GetPingResponce:
      properties:
        ping:
          type: string
          title: Ping
      type: object
      required:
        - ping
      title: GetPingResponce
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
  securitySchemes:
    SessionCookie:
      type: apiKey
      in: cookie
      name: session
