/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetOAuthRedirectResponse
 */
export interface GetOAuthRedirectResponse {
  /**
   *
   * @type {string}
   * @memberof GetOAuthRedirectResponse
   */
  redirectUri: string;
}

export function GetOAuthRedirectResponseFromJSON(
  json: any,
): GetOAuthRedirectResponse {
  return GetOAuthRedirectResponseFromJSONTyped(json, false);
}

export function GetOAuthRedirectResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetOAuthRedirectResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    redirectUri: json["redirect_uri"],
  };
}

export function GetOAuthRedirectResponseToJSON(
  value?: GetOAuthRedirectResponse | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    redirect_uri: value.redirectUri,
  };
}
