/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetPingResponce
 */
export interface GetPingResponce {
  /**
   *
   * @type {string}
   * @memberof GetPingResponce
   */
  ping: string;
}

export function GetPingResponceFromJSON(json: any): GetPingResponce {
  return GetPingResponceFromJSONTyped(json, false);
}

export function GetPingResponceFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GetPingResponce {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    ping: json["ping"],
  };
}

export function GetPingResponceToJSON(value?: GetPingResponce | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    ping: value.ping,
  };
}
