/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ImageResponse
 */
export interface ImageResponse {
  /**
   *
   * @type {string}
   * @memberof ImageResponse
   */
  base64Bytes: string;
}

export function ImageResponseFromJSON(json: any): ImageResponse {
  return ImageResponseFromJSONTyped(json, false);
}

export function ImageResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ImageResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    base64Bytes: json["base64_bytes"],
  };
}

export function ImageResponseToJSON(value?: ImageResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    base64_bytes: value.base64Bytes,
  };
}
