/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Ingredient
 */
export interface Ingredient {}

export function IngredientFromJSON(json: any): Ingredient {
  return IngredientFromJSONTyped(json, false);
}

export function IngredientFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Ingredient {
  return json;
}

export function IngredientToJSON(value?: Ingredient | null): any {
  return value;
}
