/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Instruction
 */
export interface Instruction {}

export function InstructionFromJSON(json: any): Instruction {
  return InstructionFromJSONTyped(json, false);
}

export function InstructionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Instruction {
  return json;
}

export function InstructionToJSON(value?: Instruction | null): any {
  return value;
}
