/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserInput
 */
export interface UserInput {
  /**
   *
   * @type {string}
   * @memberof UserInput
   */
  text: string;
}

export function UserInputFromJSON(json: any): UserInput {
  return UserInputFromJSONTyped(json, false);
}

export function UserInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    text: json["text"],
  };
}

export function UserInputToJSON(value?: UserInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    text: value.text,
  };
}
